In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
svi = gpd.read_file('/Users/jparkgeo/Git_Repo/population_vulnerable_to_dam_failure/SVI2020_US/SVI2020_US_tract.shp')
svi

,ST,STATE,ST_ABBR,STCNTY,COUNTY,FIPS,LOCATION,RPL_THEMES,AREA_SQMI,E_TOTPOP,...,F_MUNIT,F_MOBILE,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,SHAPE_STAr,SHAPE_STLe,geometry
0,01,Alabama,AL,01001,Autauga,01001020100,"Census Tract 201, Autauga County, Alabama",0.2395,3.793570,1941,...,0,0,0,0,0,0,0,0.000949,0.150118,"POLYGON ((-86.50910 32.47349, -86.50577 32.475..."
1,01,Alabama,AL,01001,Autauga,01001020200,"Census Tract 202, Autauga County, Alabama",0.4716,1.282174,1757,...,0,0,0,0,1,1,1,0.000318,0.092328,"POLYGON ((-86.48093 32.48154, -86.47945 32.485..."
2,01,Alabama,AL,01001,Autauga,01001020300,"Census Tract 203, Autauga County, Alabama",0.5053,2.065364,3694,...,0,0,0,0,0,0,0,0.000516,0.100175,"POLYGON ((-86.47087 32.47573, -86.46964 32.478..."
3,01,Alabama,AL,01001,Autauga,01001020400,"Census Tract 204, Autauga County, Alabama",0.2835,2.464984,3539,...,0,0,0,0,0,0,1,0.000607,0.113935,"POLYGON ((-86.45394 32.49318, -86.45308 32.493..."
4,01,Alabama,AL,01001,Autauga,01001020501,"Census Tract 205.01, Autauga County, Alabama",0.3514,2.395243,4306,...,0,0,0,0,0,0,0,0.000597,0.108866,"POLYGON ((-86.43816 32.45069, -86.43773 32.451..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84117,56,Wyoming,WY,56043,Washakie,56043000200,"Census Tract 2, Washakie County, Wyoming",0.4573,2231.951436,3124,...,0,0,0,0,0,0,0,0.648657,4.553260,"POLYGON ((-108.55063 44.15179, -108.55056 44.1..."
84118,56,Wyoming,WY,56043,Washakie,56043000301,"Census Tract 3.01, Washakie County, Wyoming",0.4879,0.769579,2231,...,0,0,0,0,0,0,0,0.000224,0.062798,"POLYGON ((-107.96833 44.00860, -107.96412 44.0..."
84119,56,Wyoming,WY,56043,Washakie,56043000302,"Census Tract 3.02, Washakie County, Wyoming",0.5299,5.957251,2578,...,0,0,0,0,0,0,0,0.001806,0.328656,"POLYGON ((-107.99537 43.98005, -107.99319 43.9..."
84120,56,Wyoming,WY,56045,Weston,56045951100,"Census Tract 9511, Weston County, Wyoming",0.6161,2355.222335,3276,...,0,1,0,0,1,2,2,0.683039,4.006506,"POLYGON ((-105.08078 43.96622, -105.07928 44.1..."
84121,56,Wyoming,WY,56045,Weston,56045951300,"Census Tract 9513, Weston County, Wyoming",0.3768,42.781557,3666,...,0,0,0,0,0,0,0,0.012426,0.599342,"POLYGON ((-104.34620 43.87346, -104.34369 43.8..."

In [11]:
len([col for col in svi.columns.tolist() if col.startswith('EP_')])

24

In [10]:
[col for col in svi.columns.tolist() if col.startswith('EP_')]

['EP_POV150',
 'EP_UNEMP',
 'EP_HBURD',
 'EP_NOHSDP',
 'EP_UNINSUR',
 'EP_AGE65',
 'EP_AGE17',
 'EP_DISABL',
 'EP_SNGPNT',
 'EP_LIMENG',
 'EP_MINRTY',
 'EP_MUNIT',
 'EP_MOBILE',
 'EP_CROWD',
 'EP_NOVEH',
 'EP_GROUPQ',
 'EP_NOINT',
 'EP_AFAM',
 'EP_HISP',
 'EP_ASIAN',
 'EP_AIAN',
 'EP_NHPI',
 'EP_TWOMORE',
 'EP_OTHERRA']

In [5]:
print(svi.columns.tolist())

['ST', 'STATE', 'ST_ABBR', 'STCNTY', 'COUNTY', 'FIPS', 'LOCATION', 'RPL_THEMES', 'AREA_SQMI', 'E_TOTPOP', 'M_TOTPOP', 'E_HU', 'M_HU', 'E_HH', 'M_HH', 'E_POV150', 'M_POV150', 'E_UNEMP', 'M_UNEMP', 'E_HBURD', 'M_HBURD', 'E_NOHSDP', 'M_NOHSDP', 'E_UNINSUR', 'M_UNINSUR', 'EP_POV150', 'MP_POV150', 'EP_UNEMP', 'MP_UNEMP', 'EP_HBURD', 'MP_HBURD', 'EP_NOHSDP', 'MP_NOHSDP', 'EP_UNINSUR', 'MP_UNINSUR', 'EPL_POV150', 'EPL_UNEMP', 'EPL_HBURD', 'EPL_NOHSDP', 'EPL_UNINSU', 'SPL_THEME1', 'RPL_THEME1', 'E_AGE65', 'M_AGE65', 'E_AGE17', 'M_AGE17', 'E_DISABL', 'M_DISABL', 'E_SNGPNT', 'M_SNGPNT', 'E_LIMENG', 'M_LIMENG', 'EP_AGE65', 'MP_AGE65', 'EP_AGE17', 'MP_AGE17', 'EP_DISABL', 'MP_DISABL', 'EP_SNGPNT', 'MP_SNGPNT', 'EP_LIMENG', 'MP_LIMENG', 'EPL_AGE65', 'EPL_AGE17', 'EPL_DISABL', 'EPL_SNGPNT', 'EPL_LIMENG', 'SPL_THEME2', 'RPL_THEME2', 'E_MINRTY', 'M_MINRTY', 'EP_MINRTY', 'MP_MINRTY', 'EPL_MINRTY', 'SPL_THEME3', 'RPL_THEME3', 'E_MUNIT', 'M_MUNIT', 'E_MOBILE', 'M_MOBILE', 'E_CROWD', 'M_CROWD', 'E_NOVEH', 'M_NOVEH', 'E_GROUPQ', 'M_GROUPQ', 'EP_MUNIT', 'MP_MUNIT', 'EP_MOBILE', 'MP_MOBILE', 'EP_CROWD', 'MP_CROWD', 'EP_NOVEH', 'MP_NOVEH', 'EP_GROUPQ', 'MP_GROUPQ', 'EPL_MUNIT', 'EPL_MOBILE', 'EPL_CROWD', 'EPL_NOVEH', 'EPL_GROUPQ', 'SPL_THEME4', 'RPL_THEME4', 'SPL_THEMES', 'E_DAYPOP', 'E_NOINT', 'M_NOINT', 'E_AFAM', 'M_AFAM', 'E_HISP', 'M_HISP', 'E_ASIAN', 'M_ASIAN', 'E_AIAN', 'M_AIAN', 'E_NHPI', 'M_NHPI', 'E_TWOMORE', 'M_TWOMORE', 'E_OTHERRAC', 'M_OTHERRAC', 'EP_NOINT', 'MP_NOINT', 'EP_AFAM', 'MP_AFAM', 'EP_HISP', 'MP_HISP', 'EP_ASIAN', 'MP_ASIAN', 'EP_AIAN', 'MP_AIAN', 'EP_NHPI', 'MP_NHPI', 'EP_TWOMORE', 'MP_TWOMORE', 'EP_OTHERRA', 'MP_OTHERRA', 'F_POV150', 'F_UNEMP', 'F_HBURD', 'F_NOHSDP', 'F_UNINSUR', 'F_THEME1', 'F_AGE65', 'F_AGE17', 'F_DISABL', 'F_SNGPNT', 'F_THEME2', 'F_MINRTY', 'F_LIMENG', 'F_THEME3', 'F_MUNIT', 'F_MOBILE', 'F_CROWD', 'F_NOVEH', 'F_GROUPQ', 'F_THEME4', 'F_TOTAL', 'SHAPE_STAr', 'SHAPE_STLe', 'geometry']

In [2]:
state = pd.read_csv('/Users/jparkgeo/Git_Repo/agingdam/dam_risk/tiger_tract_2020/state_lookup.csv')
state = state.loc[state['ContiguousUS'] == 1].reset_index(drop=True)
state['FIPS'] = state['FIPS'].astype(str)
state['FIPS'] = state.apply(lambda x: '0'+x['FIPS'] if len(x['FIPS']) == 1 else x['FIPS'], axis=1)
state

                    Name Abbr FIPS  ContiguousUS
0                Alabama   AL   01             1
1                Arizona   AZ   04             1
2               Arkansas   AR   05             1
3             California   CA   06             1
4               Colorado   CO   08             1
5            Connecticut   CT   09             1
6               Delaware   DE   10             1
7   District of Columbia   DC   11             1
8                Florida   FL   12             1
9                Georgia   GA   13             1
10                 Idaho   ID   16             1
11              Illinois   IL   17             1
12               Indiana   IN   18             1
13                  Iowa   IA   19             1
14                Kansas   KS   20             1
15              Kentucky   KY   21             1
16             Louisiana   LA   22             1
17                 Maine   ME   23             1
18              Maryland   MD   24             1
19         Massachusetts   MA   25             1
20              Michigan   MI   26             1
21             Minnesota   MN   27             1
22           Mississippi   MS   28             1
23              Missouri   MO   29             1
24               Montana   MT   30             1
25              Nebraska   NE   31             1
26                Nevada   NV   32             1
27         New Hampshire   NH   33             1
28            New Jersey   NJ   34             1
29            New Mexico   NM   35             1
30              New York   NY   36             1
31        North Carolina   NC   37             1
32          North Dakota   ND   38             1
33                  Ohio   OH   39             1
34              Oklahoma   OK   40             1
35                Oregon   OR   41             1
36          Pennsylvania   PA   42             1
37          Rhode Island   RI   44             1
38        South Carolina   SC   45             1
39          South Dakota   SD   46             1
40             Tennessee   TN   47             1
41                 Texas   TX   48             1
42                  Utah   UT   49             1
43               Vermont   VT   50             1
44              Virginia   VA   51             1
45            Washington   WA   53             1
46         West Virginia   WV   54             1
47             Wisconsin   WI   55             1
48               Wyoming   WY   56             1

In [3]:
for state_num in state['FIPS']:
    block = gpd.read_file(f'/Users/jparkgeo/Git_Repo/agingdam/dam_risk/tiger_block_2020/tl_2020_{state_num}_tabblock20')
    block = block[['GEOID20', 'HOUSING20', 'POP20', 'geometry']]
    block.rename(columns={'GEOID20': 'GEOID'}, inplace=True) 
    block = block.to_crs(epsg=4326)
    block.to_file(f'/Users/jparkgeo/Git_Repo/population_vulnerable_to_dam_failure/census_geometry/tl_2020_{state_num}_tabblock20.geojson')
    print(state_num, block.crs.name)

01 WGS 84
04 WGS 84
05 WGS 84
06 WGS 84
08 WGS 84
09 WGS 84
10 WGS 84
11 WGS 84
12 WGS 84
13 WGS 84
16 WGS 84
17 WGS 84
18 WGS 84
19 WGS 84
20 WGS 84
21 WGS 84
22 WGS 84
23 WGS 84
24 WGS 84
25 WGS 84
26 WGS 84
27 WGS 84
28 WGS 84
29 WGS 84
30 WGS 84
31 WGS 84
32 WGS 84
33 WGS 84
34 WGS 84
35 WGS 84
36 WGS 84
37 WGS 84
38 WGS 84
39 WGS 84
40 WGS 84
41 WGS 84
42 WGS 84
44 WGS 84
45 WGS 84
46 WGS 84
47 WGS 84
48 WGS 84
49 WGS 84
50 WGS 84
51 WGS 84
53 WGS 84
54 WGS 84
55 WGS 84
56 WGS 84